# This workflow is used to create 2 new branches ie., dev and testing 
# when repositories are created using this template repository. 
# This workflow also deletes itself in the created repositories.

name: Create Branches

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # The following job will create a testing branch and adds all required files to the branch
      # And job uses basic git commands for creating branches and adding files
    - run: |
        git config --local user.email "admin@vlabs.ac.in"
        git config --local user.name "vleadadmin"
        git checkout -b testing
        ls -al
        git add README.md experiment pedagogy storyboard .github/workflows/deployment-script.yml -f
        git commit -m "Testing branch created."
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ORG_OWNER_GITHUB_TOKEN }}
        force: true
        branch: testing
    - uses: actions/checkout@v2
    # The following job will delete the script that creates dev and testing branches 
    - run: |
        git checkout main
        git rm -rf .github/workflows/create-branches.yml
        git commit -m "Script which created dev and testing branches is deleted."

# Reference : https://github.com/marketplace/actions/github-push
